version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: creditdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: sh -c "python ./manage.py migrate && gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    working_dir: /code/credit_approval_system
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A backend worker -l info
    volumes:
      - .:/code
    working_dir: /code/credit_approval_system
    depends_on:
      - db
      - redis

volumes:
  postgres-data:
